### ISSUE TITLE
mat4::Transposed does not transpose the 4th column and row

### ISSUE THREAD

**Issue by knnyism** [jbikker/tmpl8#1]
At `tmpl8math.h line 669`, the function mat4::Transposed,
```cpp
CHECK_RESULT mat4 Transposed() const
{
	mat4 M;
	M[0] = cell[0], M[1] = cell[4], M[2] = cell[8];
	M[4] = cell[1], M[5] = cell[5], M[6] = cell[9];
	M[8] = cell[2], M[9] = cell[6], M[10] = cell[10];
	return M;
}
```

leaves out the 4th column and row for transposition, which is not intended behavior.

A simple fix would be:
```cpp
CHECK_RESULT mat4 Transposed() const
{
	mat4 M;
	M[0] = cell[0], M[1] = cell[4], M[2] = cell[8], M[3] = cell[12];
	M[4] = cell[1], M[5] = cell[5], M[6] = cell[9], M[7] = cell[13];
	M[8] = cell[2], M[9] = cell[6], M[10] = cell[10], M[11] = cell[14];
	M[12] = cell[3], M[13] = cell[7], M[14] = cell[11], M[15] = cell[15];
	return M;
}
```

**Comment by jbikker** [comment]
This function originally existed as a cheap alternative to mat4::Invert: transposing a 3x3 orthonormal matrix has the same effect. Although the function would still be useful for inverting matrices applied to vectors (where translation is omitted), the generality suggested by its name is misleading. I think it is thus best to expand the functionality with your proposed change.

**Comment by jbikker** [comment]
If you make this a pull request your name will properly show up as a contributor. :)

**Comment by knnyism** [comment]
The [PR](https://github.com/jbikker/tmpl8/pull/2) is up!
